sudo: required
# need a copy of docker 
services:
  - docker

# build docker with docker cli command for automation
before_install:
  - docker build -t rob/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rob/docker-react npm run test 

#TravicCI has lots of providers
deploy: 
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docke-react"
  environment: "DockeReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-208624173923"
  bucket_path: "docke-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"